[package]
name = "oudia-rs"
version = "0.1.3"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "oudia-rs is a library for loading OuDia files (`.oud`)."
repository = "https://github.com/akashiyaki01c/oudia-rs"
keywords = ["oudia"]

[dependencies]
encoding_rs = "0.8.41"
itertools = "0.15.0"
thiserror = "2.0.20"
